### ISSUE TITLE
On larger signs 0,0 is displayed as 0,9

### ISSUE THREAD

**Issue by harperreed** [briggySmalls/pyflipdot#1]
I have a 96x16 Hanover sign. This code works perfectly except that it starts on the 9 dot from the top. 

To replicate I push a numpy array that is only the first pixel as true. Such as: 

      [[ True False False ... False False False]
      [False False False ... False False False]
      [False False False ... False False False]
      ...
      [False False False ... False False False]
      [False False False ... False False False]
      [False False False ... False False False]]

The result is that the one dot is rendered mid sign instead of 0,0 as i would expect. 

Photo: 

![Screenshot from 2019-06-24 15-03-13](https://user-images.githubusercontent.com/18504/60048206-4004ee00-9691-11e9-8092-a51ed23cb217.png)

here it is using the textwriter.py to display the time: 
![Screenshot from 2019-06-24 15-03-23](https://user-images.githubusercontent.com/18504/60048227-4b581980-9691-11e9-926c-9ffc906b9d67.png)

Let me know if you have ideas on how to fix. I don't mind doing the work - but don't know where to start without starting from scratch. 

Thanks for the lib. it is much better than the alternatives ;)

**Comment by briggySmalls** [comment]
Hi there! Thanks for the issue. Nice that someone else gets some use out of this repo :)

So the sign receives pixel information as a series of bytes, where each byte is a column of 8 pixels. It sends bytes 'column-major', meaning that it sends all the necessary bytes to define column 0 before moving on to colume 1.

What this looks like is that for signs that have more than 8 pixels tall (i.e. multiple bytes needed to define a single column) there is a bug that sends them in the wrong order.

I went back to the [original repo](https://github.com/ks156/Hanover_Flipdot) that decoded the protocol (which was developed with taller signs like yours in mind) and AFAIK this _is_ the problem.

I've just opened a pull request #2 to make a change to fix the source of the error. But I'd really like for you to test it out for me before I merge it in.

**Comment by harperreed** [comment]
Sounds good. I will test in the morning.

**Comment by harperreed** [comment]
Tested the pull request. It worked as described. Once merged - it will solve this issue

**Comment by briggySmalls** [comment]
Release should now be available on pypi/via pip!
