### ISSUE TITLE
The script cannot support board like 128 * 32

### ISSUE THREAD

**Issue by anthonykhy** [briggySmalls/pyflipdot#4]
the image will be too large, see below error  

File "/usr/local/lib/python3.6/dist-packages/pyflipdot/data.py", line 23, in _to_ascii_hex
    return _bytes_to_ascii_hex(value)
  File "/usr/local/lib/python3.6/dist-packages/pyflipdot/data.py", line 20, in _bytes_to_ascii_hex
    return val.hex().upper().encode('ASCII')

**Comment by anthonykhy** [comment]
for example using 128*32

**Comment by briggySmalls** [comment]
Hi Anthony! Thanks for creating this issue and I'm sorry the driver didn't work for you straight away. I'm looking into the issue now and should get a fix out soon!

**Comment by briggySmalls** [comment]
I have made a new release with the change merged in.

You should be able to obtain this release shortly, using `pip install pyflipdot` or `pip install --upgrade pyflipdot` if you've already got it installed.

As I don't have such a sign myself, I'd love to hear from you to see if it is working now!
